# -*- coding: utf-8 -*-
"""Shared desktop application environment variable names."""

DESKTOP_APP_ENV = "QWENPAW_DESKTOP_APP"
DESKTOP_PORT_ENV = "QWENPAW_DESKTOP_PORT"
DESKTOP_CORS_ORIGINS_ENV = "QWENPAW_CORS_ORIGINS"
DESKTOP_BACKEND_LOG_ENV = "QWENPAW_TAURI_BACKEND_LOG"
