# -*- coding: utf-8 -*-
"""Constants for the WeCom custom channel plugin."""

DEFAULT_BOT_PREFIX = "[BOT] "
DEFAULT_MEDIA_DIR = "~/.copaw/media/wecom"
DEFAULT_PROCESSED_IDS_MAX_ITEMS = 1024
DEFAULT_ROUTES_FILE = "wecom_routes.json"
DEFAULT_PROCESSED_IDS_FILE = "wecom_processed_ids.json"
DEFAULT_WS_URL = "wss://openws.work.weixin.qq.com"
DEFAULT_HEARTBEAT_INTERVAL_SECONDS = 30
DEFAULT_PING_INTERVAL_SECONDS = DEFAULT_HEARTBEAT_INTERVAL_SECONDS
DEFAULT_RECONNECT_MIN_SECONDS = 1
DEFAULT_RECONNECT_MAX_SECONDS = 30

TO_HANDLE_PREFIX = "wecom"
TO_HANDLE_KIND_USER = "user"
TO_HANDLE_KIND_CHAT = "chat"
TO_HANDLE_KIND_WEBHOOK = "webhook"
WECOM_CHAT_TYPE_SINGLE = 1
WECOM_CHAT_TYPE_GROUP = 2
